####################################################
#   Hello This is The Config file for the plugin   #
#                  Hardcore Quest                  #
#                                                  #
#  This Plugin was created by the DoggyCraft team  #
#                You can find us at                #
#         https://github.com/DoggyCraftDK/         #
#   If you have questions, a bug or just an idea   #
#                Please let us know                #
####################################################
# If you receive an error when you load this plugin
# Make sure that:
# There are no taps
# Text with symbols is enclosed in single or double quotation marks

# This sets you server name:
ServerName: 'YourServerName'

#This Sets Something Else in the Future
SomethingElse: 5