name: HardcoreQuest
main: dk.doggycraft.hq.HardcoreQuest
version: 0.0.1
description: A quest where only the best players survive!
softdepend: [Vault, PermissionsBukkit, PermissionsEx, bPermissions, GroupManager]
commands:
  hardcorequest:
    usage: /<command>
    description: A useless command.
  hq:
    usage: /<command> startquest
    description: A useless command.
  quest:
    usage: /<command>
    description: A useless command.
permissions:
  hq.*
    description: Gives permission to all HardcoreQuest commands.
    children:
      hq.startquest
  hq.startquest:
    description: Permission to start a quest.
    default: false
